#!/bin/bash
# /ops/backup/restore.sh

set -e
set -o pipefail

# --- Defaults and Configuration ---
PG_HOST=${PG_HOST:-localhost}
PG_PORT=${PG_PORT:-5432}
PG_USER=${PG_USER:-admin}

# --- Helper Functions ---
function print_usage() {
    echo "Usage: ./restore.sh <backup_dir> <db_name> [target_db_name]"
    echo ""
    echo "Restores a PostgreSQL database from a backup directory generated by the backup service."
    echo ""
    echo "Arguments:"
    echo "  <backup_dir>      Path to the backup directory (e.g., /backups/20231103T102030Z)."
    echo "  <db_name>         The original name of the database to restore (e.g., PersonalGrowthDb)."
    echo "  [target_db_name]  Optional. The name of the new database to restore into. Defaults to <db_name>_restored."
    echo ""
    echo "Environment Variables:"
    echo "  PG_HOST, PG_PORT, PG_USER, PGPASSWORD can be set to configure the connection."
}

# --- Input Validation ---
if [[ -z "$1" || -z "$2" ]]; then
    echo "Error: Backup directory and database name are required."
    print_usage
    exit 1
fi

BACKUP_DIR=$1
DB_NAME=$2
TARGET_DB_NAME=${3:-${DB_NAME}_restored}

# Find the dump file in the backup directory
DUMP_FILE=$(find "$BACKUP_DIR" -name "pg-${DB_NAME}.dump" | head -n 1)

if [[ ! -f "$DUMP_FILE" ]]; then
    echo "Error: Dump file for database '$DB_NAME' not found in '$BACKUP_DIR'."
    exit 1
fi

if [[ -z "$PGPASSWORD" ]]; then
    echo -n "Enter PostgreSQL password for user '$PG_USER': "
    read -s PGPASSWORD
    export PGPASSWORD
    echo
fi

# --- Restore Process ---
echo "Starting restore of '$DB_NAME' from '$DUMP_FILE' to database '$TARGET_DB_NAME'..."

# 1. Drop target database if it exists (with confirmation)
read -p "WARNING: This will drop the database '$TARGET_DB_NAME' if it exists. Continue? (y/N) " confirm
if [[ ! "$confirm" =~ ^[yY]$ ]]; then
    echo "Restore cancelled."
    exit 0
fi

echo "Dropping existing database '$TARGET_DB_NAME'..."
dropdb --if-exists -h "$PG_HOST" -p "$PG_PORT" -U "$PG_USER" "$TARGET_DB_NAME"

# 2. Create a new, empty database
echo "Creating new database '$TARGET_DB_NAME'..."
createdb -h "$PG_HOST" -p "$PG_PORT" -U "$PG_USER" -O "$PG_USER" "$TARGET_DB_NAME"

# 3. Restore the dump into the new database
echo "Restoring data using pg_restore..."
pg_restore -h "$PG_HOST" -p "$PG_PORT" -U "$PG_USER" -d "$TARGET_DB_NAME" -v --no-owner --no-privileges "$DUMP_FILE"

echo ""
echo "✅ Restore completed successfully."
echo "Database '$DB_NAME' has been restored to '$TARGET_DB_NAME' on host '$PG_HOST'."
